version: '3.8'
services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: 'my_database'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
  redis:
    image: "redis"
    ports:
      - "6379:6379"

volumes:
  db-data:
